feat: use the verified image sha to run the container (#107)
* feat: use verified sha to run image

Signed-off-by: Ian Lewis <ian@ianlewis.org>

* feat: use dynamic image names

Signed-off-by: Ian Lewis <ian@ianlewis.org>

* chore: check if jq is installed

Signed-off-by: Ian Lewis <ian@ianlewis.org>

---------

Signed-off-by: Ian Lewis <ian@ianlewis.org>

diff --git a/bin/claude b/bin/claude
--- a/bin/claude
+++ b/bin/claude
@@ -43,6 +43,13 @@ if ! command -v cosign >/dev/null 2>&1; then
     exit 1
 fi
 
+if ! command -v jq >/dev/null 2>&1; then
+    echo "jq is not installed. Please install jq first." >&2
+    echo "Please see this URL for installation instructions:" >&2
+    echo "https://jqlang.org/download/" >&2
+    exit 1
+fi
+
 CLAUDE_CODE_IMAGE="ghcr.io/ianlewis/claude-code"
 
 XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
@@ -56,23 +63,29 @@ if [ ! -f "${CLAUDE_DATA_HOME}/claude.json" ]; then
     echo "{}" >"${CLAUDE_DATA_HOME}/claude.json"
 fi
 
-cosign verify-attestation \
+verified_sha=$(cosign verify-attestation \
     --type slsaprovenance \
     --certificate-oidc-issuer https://token.actions.githubusercontent.com \
     --certificate-identity-regexp '^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v[0-9]+.[0-9]+.[0-9]+$' \
     --policy ~/.config/coding-assistant-docker-images/policy.cue \
-    "${CLAUDE_CODE_IMAGE}"
+    "${CLAUDE_CODE_IMAGE}" | jq -r '.payload' | base64 -d | jq -r '.subject[0].digest.sha256')
+
+if [ -z "${verified_sha}" ]; then
+    echo "Failed to verify the image signature." >&2
+    exit 1
+fi
+
+echo "Verified image: ${CLAUDE_CODE_IMAGE}:sha256:${verified_sha}"
 
 # Ensure we have the latest image
-docker pull "${CLAUDE_CODE_IMAGE}"
+docker pull "${CLAUDE_CODE_IMAGE}@sha256:${verified_sha}"
 
 docker run \
     --rm \
     --interactive \
     --tty \
-    --name claude-code \
     --runtime runsc \
     --volume "$(pwd):/workspace" \
     --volume "${CLAUDE_DATA_HOME}/claude.json:/claude.json" \
     --volume "${CLAUDE_DATA_HOME}:/claude" \
-    "${CLAUDE_CODE_IMAGE}" claude "$@"
+    "${CLAUDE_CODE_IMAGE}@sha256:${verified_sha}" claude "$@"
